import Head from 'next/head';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Next-Shop',
  description: 'Generated by my-next-shop',
};

export default function Layout({
  children,
}: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
      </Head>
      <div>
        {children}
      </div>
    </>
  );
}
