import HomePage from '@/components/Main/MainPage';
import Head from 'next/head';

export const metadata = {
  title: 'Next-Shop',
  description: 'Generated by my-next-shop',
};

export default function Home() {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
      </Head>
      <HomePage />
    </>
  );
}
